### PR TITLE
Simple travis compile tests

### PR DESCRIPTION
**Pull request by stephengroat**
If you like this, I can also show you how to get `mingw-w64` easily as well

### CODE REVIEW

**Comment by cederom** [comment]
Hello @stephengroat :-) Thanks for Travis scripts! I usually work with CLANG (FreeBSD/macOS) and GCC (Linux), but yes please add more compilers so we can know possible problems :-)

Also please remember about two possible build types:
* `./configure` will build only the library (default).
* `./configure --enable-application` will also build the LibSWD application and here more problems may show up.

**Comment by stephengroat** [comment]
thanks for the info, updated for `--enable-application` and added `osx` builds

**Comment by cederom** [comment]
Thanks! Please keep two build test with and without application :-)

**Comment by cederom** [comment]
no `make test` is provided sir! i can zee "some checks haven't completed yet".. will wait a bit untils all wergkz :-)

**Comment by cederom** [comment]
no dependencies are required for the bare library. application may require `libftdi`, `readline`, and maybe `libusb`..

**Comment by stephengroat** [comment]
seems to compile with just `libftdi` on `linux`

`osx` takes **forever** to schedule, so i'll squash the commit once those have run to make sure they work

**Comment by cederom** [comment]
This GitHub+Travis integration looks awsome, we can even build test code before its merged into the upstream! :-)

No rush, take your time, we will merge when ready :-)

**Comment by stephengroat** [comment]
I've also added tea-ci.org, which is a free msys (for mingw) ci env.

https://tea-ci.org/stephengroat/LibSWD

I'm getting close on that too, just have to libftdi issues

**Comment by stephengroat** [comment]
squashed.

has working travis-ci and tea-ci on all builds (including mingw-w64)

let me know what you want to do about the `strsep` and `#include` issues. `mingw` doesn't seem to want to ever do `strsep`, but is there an easy way to require `gnulib` for `mingw` builds? (http://git.net/ml/gnu.mingw.user/2002-10/msg00489.html)

**Comment by cederom** [comment]
Uhm, never tries windows/mingw before, not really fan of M$, thanks for the updates!

Do we want to define windows in the os list as there is linux and osx already and we addedd mingw support?

Redy to pull? :-)

**Comment by stephengroat** [comment]
I've realized that for `mingw`, you'll need to get `strsep` in there. you could use `gnulib`, but that's a lot of import.

do you really want `mingw` support?

**Comment by cederom** [comment]
not really =) but also maybe its good time to replace `strsep` with something more portable.. :-)

**Comment by stephengroat** [comment]
cleaned up and ready to go. sorry about being lazy for a while

**Comment by cederom** [comment]
Awsome work! Thank you @stephengroat! =)

**Pull request merged**
