### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by andrewparlane**
Dealing correctly with 8, 16 or 32 bit read and writes correctly. Using the correct byte-laning, and checking for alignment issues.
Bits of tidying up (whitespace, unused vars, etc..)
A bit of an optimisation when reading CPUID.

### CODE REVIEW

**Comment by cederom** [comment]
Hey Andrew! Thanks for your patches! I will review the changes and talk back to you :-)

**Comment by cederom** [comment]
All looks great! Awsome work! Thank you Andrew! Except for that two changes that I would prefer not to include because of the design reasons/philosphy:
* e79b5b2: DEBUG: Added a define for number of supported CPUIDs. - That would be okay for the constant size of the structure, while our structure can have entries of different sizes, and we also may want to extend this structure freely, while that would not be possible after proposed commit. This is why I assumed first entry identification would be more versatile.
* 071d6e0: DEBUG: Don't re-read the CPUID register for every target. - This is the most important step of connection phase to read the identification register for the CPU, based on which we can apply further program tuning, this is why we may sacrifice some time for better detection rather than speeding up by limiting the devices support list (i.e. custom made, multicore, CPU with this register at different location, etc).

The `libswd-application` was only a simple test to see and present how LibSWD works. I had really no  plans to extend it here, but as an external application (see my [iCeDeROM](https://github.com/cederom/iCeDeROM) project). Your patches are highly welcome and appreciated! I will include them except for two mentioned above if that is okay for you..? :-)

**Comment by andrewparlane** [comment]
Hey no worries. Just fixing things when I see them / need them.

e79b5b2: DEBUG: Added a define for number of supported CPUIDs. - I'm not
sure I understand what you mean here. The size of each element of
the libswd_arm_register_t [] has size of sizeof(libswd_arm_register_t). The
define I added works out the number of elements in that array. You can add
more or remove some or whatever, it'll always give the correct number of
elements. Also when you say "we also may want to extend this structure
freely", what do you mean by extend, as in have another struct derived from
this one with all the polymorphism that it gives. As it is all that code is
C, and didn't even compile using my x86 c++ toolchain, I had to compile it
as C. So I think if we decided to extend that struct, we'd have a bunch of
work ahead of us before this became an issue, and it would be a relatively
simple change at that point.

071d6e0: DEBUG: Don't re-read the CPUID register for every target. - My
logic here was that all the supported chips so far used the same address
for the register, and I've seen no indication that any chip that supports
SWD uses a different address. That's not to say they don't exist. However I
figured we could at that point rework that bit of code to deal with that.
Something like having a list of registers where the IDCODE could be stored,
and each of those has a pointer to a list of values for supported chips. IE.

IDCodeAt_E000ED00_Chips [] =
{
  {
    .name="ARM Cortex-M3 r2p1",
    .default_value=0x412FC231
  },
  {
    .name="OTHER CHIP",
    .default_value=0xFOOBAR
  },
};

IDCodeAt_OTHER_ADDR_Chips [] =
{
  {
    .name="BLAH",
    .default_value=...
  },
  {
    .name="BLAH BLAH",
    .default_value=...
  },
};

IDCodes [] =
{
  {
    .addr = 0xE000ED00,
    .chips = &IDCodeAt_E000ED00_Chips,
    .num_chips = ARRAY_ITEMS(IDCodeAt_E000ED00_Chips)
  },
  {
    .addr = ...,
    .chips = &IDCodeAt_OTHER_ADDR_Chips,
    .num_chips = ARRAY_ITEMS(IDCodeAt_OTHER_ADDR_Chips)
  }
};

Then we can iterate over addresses and then check the value against each
chip for that address.

I could do this work and resubmit the patch, or we can just revert it. It's
your project after all.

Thanks,
Andy

**Comment by cederom** [comment]
Okay @andrewparlane we can make changes when necessary you are right! Your work is much appreciated! Thank you!! :-)

**Comment by cederom** [comment]
@andrewparlane please make any suggestions and changes I think its high time for another release! :-)

**Comment by cederom** [comment]
@andrewparlane I have just made a LibSWD-0.7 release, after 4 years!!
THIS ONE IS DEDICATED FOR YOU!! THANK YOU!! =)

**Comment by andrewparlane** [comment]
Thanks :)

I'll keep tinkering over time.

Andy

**Pull request merged**
