### PR TITLE
Fixed issues alerted by cederom:

### PR DESCRIPTION
**Pull request by ViaExplore**
- += instead of =+
- fflush is now part of a function libswd_log_flush(...)
- cmdq queue limited by variables:
	libswdctx->config.maxcmdqlen
	and
	libswdctx->stats.cmdqlen
	in function libswd_cmd_enqueue(...)
- added stats as statistics for cmd queue len
- fixed functions libswd_cmdq_free...(...) to work with stats
- added .project file for Eclipse luna with CDT
- .project configured for arm-none-eabi gcc compiler as static library
	for ARM-Cortex M3 CPU

### CODE REVIEW

**Comment by cederom** [comment]
Hello Thomas! Thank you for your changes! As you noted several TODO's were created, and so patches/commits should be split into functional groups that solves one problem at time. From a "it just works" point of view pushing several changes may work, but then its not how GIT commit works..

The `=+` solutions are fine, thanks! All of them should come as one commit.

The `libswd_log_flush()` looks good, it also should come as separate commit.

I don't really understand why did you create separate `stats` and pass it as first paramntere to some functions.. this breaks current API.. I am sure we can make queue clear without such dramatic changes..?

Regarding the Eclipse part, I would rather not implement such change/dependency.. it is user choice to select editor and its configuration.. maybe it is possible to create this kind of build with `Autotools` only?

**Comment by ViaExplore** [comment]
Hi Cederom,
this is my first push on github ever. I am used to SVN repository, apologising. Next time I will do one issue per push.

Now about the stats. Look at the function [libswd_cmd_enqueue()](https://github.com/ViaExplore/LibSWD/blob/master/src/libswd_cmd.c) and you will find my memory limit implementation which needs information from stats to work correctly:
- If you configure config.maxcmdqlen to zero, no memory limitation will be active
- If you set this to number to bigger than zero it will try to limit cmd queue len to that count. But to do this, you need to count every cmd queue free or append  changes, thus pointer to stats is passed to every libswd_cmdq_free... function and keeps this information up to date.
Well, there is a solution without stats, but it is CPU consuming process. You can count the cmd queue len by finding head and go thru chain up to tail. And if this count is bigger than X than you can try memory release. But this must be done in each libswd_cmd_enqueue call and imagine than somebody will set maxcmdqlen to big number. Also stats can be expanded by transfer speed information, total packet count and so on.

Now about the eclipse part. I do not use CLI for compiling, nor make program for setting up project. It is just no so funny with Windows. Much faster for me is simple Eclipse project which do not affect your make file, it creates his own internal one. It is just another option for compiling/using that library like make file. There are huge number of users with Eclipse and CDT plugin, and now by importing this they are ready to use without any workaround.

I see another problem, that is travis test/build system, which is not configured because of missing .travis.yml file. I found a user @stephengroat who did some patches uppon your libSWD. Look at [his solution](https://github.com/stephengroat/LibSWD), it seems very usable.

Tell me what to do/how to fix this and I will try my best :)

**Comment by cederom** [comment]
No worries, I know, first steps, thus some hints :-) But we need to act correctly right from beginning, so the current merge cannot be applied sorry :-)

LibSWD was developed on FreeBSD, VIM, CSH :-) Eclipse is a separate part.. as this does not really affect the library but your own build.

Travis is here as separate pull request, will look into it :-)

Regarding the queue, please let me consider your solution, but we cannot change API this way.. need some more work :-)

**Comment by cederom** [comment]
I have just pulled in the Travis related patches.. lets see how it works here I wonder :-)

**Review by cederom — CHANGES_REQUESTED** [review]
this commit squashes too much changes at once, we need to split them into separate commits please :-)

**Comment by cederom** [comment]
Tomas feel free to play with Git and GitHub :-) Please split functional changes into a separate commits (i.e. log fix is one commit, cmdq is another commit, etc).

I would not like to add Eclipse specific code here as this is your choice of build SDK. We only use basic shell tools here.. and it should stay that way.. as low dependencies as possible :-)

Also I can see Travis is working better now :-)

**Comment by ViaExplore** [comment]
I do not understand, each step from this morning is per one commit and push solving one issue. Eclipse project files will be removed and added to .gitignore file, but how can I upload them to my fork? To keep them for others?

**Comment by ViaExplore** [comment]
Ahaaa, I got it, OK, first thing I will roll back all changes and start again as you recommended. Then make one commit per issue, starting with log for example, then these += and as a last the memory issue.

**Pull request closed without merging**
