### PR TITLE
MEMAP: Fixing bug with auto TAR increment (Issue #15).

### PR DESCRIPTION
**Pull request by andrewparlane**
The TAR register can be auto incremented after every write or read from
DRW. However this is only guaranteed to work for the lowest 10 bits of
TAR. Above that it's implementation defined.

On some targets it's just the 10 bits, meaning that something unknown
<implementation defined> happens if you go over a !KB boundary.

The previous code dealt with this, by rewriting the TAR register every
1KB. However that doesn't work if you don't start your writes 1KB
aligned.

For example, if you write 1KB starting at address 0x200, the first 512
bytes write OK, after that it's implementation defined. On my target it
wrapped to 0 and wrote the last 512 bytes there.

My fix re-writes the TAR register whenever you hit a 1KB boundary,
regardless of start address.

### CODE REVIEW

**Comment by cederom** [comment]
Awsome work! Thanks Andy! Will look into it next week :-)

**Comment by andrewparlane** [comment]
Any problems with this?

**Comment by cederom** [comment]
Thank you @andrewparlane ! No problems.. just summertime.. sorry :-)

**Comment by andrewparlane** [comment]
NP.

**Comment by cederom** [comment]
Btw @andrewparlane have you seen the https://github.com/mbedmicro/DAPLink project? It really speeds things up compared to LibSWD over USB from the Host.. DAPLink is a firmware put on MCU that dramatically speeds things up :-)

**Comment by andrewparlane** [comment]
Sure, I've been using it on my NXP frdm boards. Unfortunately it's not set
up in a way that will work for us on our custom boards.

**Comment by cederom** [comment]
Not possible to customize? I see it running on a different boards, MCU and Targets.. looks very promising project! :-) But also nice to hear LibSWD has its unique advantages, thanks! :-)

**Pull request merged**
